childsos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from service import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter(trailing_slash=False)
router.register(r'api/cases',views.CasesViewSet)
router.register(r'api/responses',views.ResponseViewSet)
router.register(r'api/case_responses',views.CaseResponseViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.HomeView.as_view(),name='home'),
    url(r'^thankyou/$', views.ThankYouView.as_view(),name='thankyou'),
    url(r'^login/$', views.LoginView.as_view(),name='login'),
    url(r'^logout/$', views.LogoutView.as_view(),name='logout'),
    url(r'^dashboard/$', views.DashboardView.as_view(),name='dashboard'),
    url(r'^invitations/$', views.InvitationsView.as_view(),name='invitations'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration', include('rest_auth.registration.urls'))

]

service/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Invitation(models.Model):
    fullname = models.CharField(max_length=200)
    email = models.CharField(max_length=200)

class Case(models.Model):

    class Meta:
        ordering = ['-reported_date']

    # http://study.com/academy/lesson/child-abuse-and-neglect-4-major-types-characteristics-effects.html
    CASE_TYPES = (
        ('Phy', 'Physical Abuse'),
        ('N', 'Neglect'),
        ('Psy', 'Psycological Abuse'),
        ('S', 'Sexual Abuse'),
    )

    SUSPECTS = (
        (1,'Orang tua'),
        (2, 'Bapak'),
        (3, 'Ibu'),
        (4, 'Saudara Kandung'),
        (5, 'Lainnya'),
    )

    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    reported_by = models.CharField(max_length=200, null=True, blank= True)
    reported_date = models.DateTimeField(null=True, blank=True)
    phone = models.CharField(max_length=200, null= True, blank= True)
    email = models.CharField(max_length=200, null= True, blank= True)
    location = models.CharField(max_length=400, null=True, blank= True)
    longitude = models.CharField(max_length=220, null=True, blank=True)
    latitude = models.CharField(max_length=220, null=True, blank=True)
    has_response = models.BooleanField(default= False)
    case_type = models.CharField(max_length=20, null= True, blank= True)
    suspect = models.CharField(max_length=200,null=True, blank=True)
    victim = models.CharField(max_length=200,null=True,blank=True)


class CaseResponse(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    cell_phone = models.CharField(max_length=200)
    severity_level = models.IntegerField()
    responded_date = models.DateTimeField()
    case_id = models.ForeignKey(Case, related_name='case_responses')
    description = models.TextField()

    def __unicode__(self):
        return '%s: \n %s' % (self.responded_date.strftime("%b %d, %Y %H:%M:%S"), self.description)

class Responder(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200, null= True, blank= True)
    email = models.CharField(max_length=200, null= True, blank= True)
    cell_phone = models.CharField(max_length=200, null= True, blank= True)
    longitude = models.CharField(max_length=200, null= True, blank= True)
    latitude = models.CharField(max_length=200, null= True, blank=True)
    user = models.ForeignKey(User)

class Response(models.Model):
    case_id = models.ForeignKey(Case, related_name= 'responses')
    response_date = models.DateTimeField(auto_now_add= True)
    responder = models.ForeignKey(Responder)
    response_report = models.TextField()
    validity = models.IntegerField()
    severity_level = models.IntegerField()

service/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from .models import Case, Responder, Response, Invitation, CaseResponse
from .form import InvitationForm
from .serializers import CaseSerializer, ResponderSerializer, ResponseSerializer, CaseResponseSerializer
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework import mixins, viewsets
from rest_framework import generics
from rest_framework.views import APIView
from django.contrib import messages

# Create your views here.

class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)

class LoginView(TemplateView):
    template_name = 'home/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        # authenticate the account
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('dashboard'))

        return render(request,self.template_name)

class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))

class HomeView(TemplateView):
    template_name = 'home/index.html'
    def get(self, request):
        form = InvitationForm()
        return render(request,self.template_name, {'form':form})

    def post(self, request):
        invitation = None
        form = InvitationForm(request.POST or None, instance=invitation)
        if form.is_valid():
            form.save()
            messages.success(request,'Thank you for your support. We will contact you once we are ready.')
            return HttpResponseRedirect(reverse('thankyou'))
        else:
            return render(request, self.template_name, {'form':form})

class ThankYouView(TemplateView):
    template_name = 'home/thankyou.html'
    def get(self, request, *args, **kwargs):
        return render(request,self.template_name)


class DashboardView(TemplateView):
    template_name = 'case/dashboard.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

class InvitationsView(TemplateView):
    template_name = 'home/invitations.html'

    def get(self, request, *args, **kwargs):
        invitations = Invitation.objects.all()
        return render(request,self.template_name,{'invitations':invitations})

class CaseAllView(TemplateView):
    template_name = 'case/all.html'

    def get(self, request, *args, **kwargs):
        cases = Case.objects.all()
        return render(request, self.template_name, {'cases': cases})


class CaseDetailView(TemplateView):
    template_name = 'case/detail.html'
    case_id = None

    def get(self, request, case_id):
        case = get_object_or_404(Case, id=case_id)
        return render(request, self.template_name, {'case': case})

#api

class CasesViewSet(viewsets.ModelViewSet):
    queryset = Case.objects.all()
    serializer_class = CaseSerializer

class CaseResponseViewSet(viewsets.ModelViewSet):
    queryset = CaseResponse.objects.all()
    serializer_class = CaseResponseSerializer

class ResponseViewSet(viewsets.ModelViewSet):
    queryset = Response.objects.all();
    serializer_class = ResponseSerializer

templates/case/all.html
{% extends 'main_template.html' %}

{% block main %}
<h1>All Cases</h1>

    {% if cases %}
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Reported date</th>
        </tr>
        {% for case in cases %}
            <tr>
                <td><a href="{% url 'case-detail' case.id %}">{{ case.title }}</a></td>
                <td>{{ case.reported_date }}</td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No cases yet</p>
    {% endif %}
{% endblock %}

templates/case/dashboard.html
{% extends 'main_template.html' %}
{% block main %}
<h1>Welcome</h1>
{% endblock %}

templates/case/detail.html
{% extends 'main_template.html' %}
{% block main %}

    <div class="row">
        <div class="col-lg-8">
            <h1>{{ case.title }}</h1>
            <h4>Type</h4>
            {% if case.case_type == 'Phy' %}
                <p>Physical Abuse</p>
            {% elif case.case_type == 'N' %}
                <p>Neglect (Penelantaran anak)</p>
            {% elif case.case_type == 'Psy' %}
                <p>Psycological Abuse</p>
            {% elif case.case_type == 'S' %}
                <p>Sexual Abuse</p>
            {% else %}
                <p>Other</p>
            {% endif %}
            <h4>Reported at</h4>
            <p>{{ case.reported_date|date:'Y/d/m H:i:s' }}</p>
            <h4>What happened</h4>
            <p>{{ case.description }}</p>
            <h4>Location</h4>
            <p>{{ case.location }}</p>
            {% if not case.location == ''%}
                <div id="map"></div>
            {% endif %}
            <div>
                <h3>Responses</h3>
                {% if case.responses.all %}
                    <ul>
                        {% for response in responses %}
                            <li><a href="#">{{ response.response_date }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No responses yet</p>
                {% endif %}
            </div>
        </div>
    </div>
    {% if not case.location == '' %}
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        <script>
            var map;
            function Init()
            {
                // Create a Google coordinate object for where to initially center the map
                //var latlng = new google.maps.LatLng( -6.1753924,106.8271528 );	// Monas, Jakarta

                // Map options for how to display the Google map
                //var mapOptions = { zoom: 12, center: latlng  };

                // Show the Google map in the div with the attribute id 'map-canvas'.


                var geocoder = new google.maps.Geocoder();
                var address = '{{ case.location }}';
                geocoder.geocode( { 'address': address }, function(results, status) {
                    var addr_type = results[0].types[0];	// type of address inputted that was geocoded
                    if ( status == google.maps.GeocoderStatus.OK ) {
                        console.log(results[0].geometry.location);
                        ShowLocation(results[0].geometry.location, address, addr_type);

                    }
                    else {
                        alert("Geocode was not successful for the following reason: " + status);
                    }
                });
            }

            function ShowLocation( latlng, address, addr_type )
            {
                var mapOptions = { zoom: 15, center: latlng  };
                // Center the map at the specified location
                map = new google.maps.Map(document.getElementById('map'), mapOptions);
                map.setCenter( latlng );

                // Set the zoom level according to the address level of detail the user specified
                switch ( addr_type )
                {
                    case "administrative_area_level_1"	: zoom = 6; break;		// user specified a state
                    case "locality"						: zoom = 10; break;		// user specified a city/town
                    case "street_address"				:
                        zoom = 15;
                        break;		// user specified a street address
                }

                // Place a Google Marker at the same location as the map center
                // When you hover over the marker, it will display the title
                var marker = new google.maps.Marker( {
                    position: latlng,
                    map: map,
                    title: address
                });

                // Create an InfoWindow for the marker
                var contentString = "" + address + "";	// HTML text to display in the InfoWindow
                var infowindow = new google.maps.InfoWindow( { content: contentString } );

                // Set event to display the InfoWindow anchored to the marker when the marker is clicked.
                google.maps.event.addListener( marker, 'click', function() { infowindow.open( map, marker ); });
            }
        google.maps.event.addDomListener( window, 'load', Init );


        </script>
    {% endif %}

{% endblock %}

templates/home/index.html
{% extends 'web_template.html' %}
{% block main %}
<div class="row">
<div class="col-lg-4 col-lg-offset-4">

        <h2>Help us save our children</h2>
        <p>
            We are launching our mobile application soon to help children from any kind of abuses. You can help us by
            becoming volunteers. Enter your email and name, we will notify you once we are ready.
        </p>
        <div>
            <form method="post" action="{% url 'home' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_fullname">Fullname</label>
                    <input type="text" class="form-control" id="id_fullname" name="fullname">
                </div>
                <div class="form-group">
                    <label for="id_email">Email</label>
                    <input type="text" class="form-control" id="id_email" name="email">
                </div>
                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/home/invitations.html
{% extends 'main_template.html' %}

{% block main %}
<h1>Invitations</h1>

    {% if invitations %}
    <table class="table">
        <tr>
            <th>Fullname</th>
            <th>Email</th>
        </tr>
        {% for invitation in invitations %}
            <tr>
                <td>{{ invitation.fullname }}</td>
                <td>{{ invitation.email }}</td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No cases yet</p>
    {% endif %}
{% endblock %}

templates/home/login.html
{% extends 'main_template.html' %}
{% block main %}
<h1>Login</h1>
    <div class="row">
    <div class="col-lg-6">
        <form action="{% url 'login' %}" method="post" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input type="text" name="username" id="id_username" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_password">Password</label>
                <input type="password" name="password" id="id_password" class="form-control">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </form>
    </div>

    </div>
{% endblock %}

templates/home/thankyou.html
{% extends 'web_template.html' %}
{% block main %}
<div class="row">
<div class="col-lg-4 col-lg-offset-4">
    <h2>Thank you</h2>
    <p>Your support means a lot for our movement. We will notify you once our application is ready. </p>
    <p><a href="{% url 'home' %}">Home</a></p>
</div>
</div>
{% endblock %}

templates/main_template.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Child SOS</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'css/plugins/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">ChildSOS Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <!--
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                -->
                {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                        {{ request.user.first_name }} <b
                            class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
                {% else %}
                    <li class="dropdown">
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav side-nav">

                    <li class="active">
                        <a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'invitations' %}"><i class="fa fa-fw fa-table"></i> Invitations</a>
                    </li>

                    <li>
                        <a href="{% url 'case-all' %}"><i class="fa fa-fw fa-bar-chart-o"></i> Cases</a>
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-fw fa-table"></i> Responders</a>
                    </li>

                </ul>
                {% endif %}
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                {% block main %}

                {% endblock %}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>



</body>

</html>

templates/web/main_template.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Tolong!</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

</body>
</html>

templates/web_template.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Tolong!</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">
    {% block main %}

    {% endblock %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>